# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/Deeply',
                'doc_host': 'https://neerajadsul.github.io',
                'git_url': 'https://github.com/neerajadsul/Deeply',
                'lib_path': 'Deeply'},
  'syms': {'Deeply.core': {'Deeply.core.foo': ('core.html#foo', 'Deeply/core.py')}}}